modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
issueTrackerURL="https://github.com/SlimeAttack07/NavalWarfare-1.18/issues" #optional
[[mods]] #mandatory
modId="naval_warfare" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Naval Warfare" #mandatory
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://www.curseforge.com/minecraft/mc-mods/naval-warfare" #optional
logoFile="logo.png" #optional
authors="SlimeAttack07" #optional
description='''
This mod allows players to play the board game battleship with a twist. There are new ship shapes to confuse your opponents,
abilities to combo into devastating attacks and utilities to throw your opponents off guard. This mod takes heavy inspiration from
a mobile app called SailCraft Battleships Online, which unfortunately  shut down on 28/08/2018 and is no longer available to play.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.examplemod]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[39,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
